# Generated by Django 5.1.5 on 2025-01-28 10:18

import users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='users_avatars/default.png', null=True, upload_to=users.utils.generate_avatar_name),
        ),
    ]
