# Generated by Django 5.1.5 on 2025-01-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='public_name',
            field=models.CharField(default='wow', max_length=50),
            preserve_default=False,
        ),
    ]
