# Generated by Django 5.1.5 on 2025-01-28 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='online',
        ),
    ]
