# Generated by Django 5.1.5 on 2025-02-18 12:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_customuser_contacts_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='user_contacts', to=settings.AUTH_USER_MODEL),
        ),
    ]
