# Generated by Django 5.1.5 on 2025-02-18 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_confirmationcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfirmationCode',
        ),
    ]
