services:
  web:
    build: .
    command: uvicorn HBT.asgi:application --host 0.0.0.0 --port 8000
    volumes:
      - .:/app  # Монтируем текущую директорию в контейнер
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DEBUG=True
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=HBT.settings
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"  # Порт Redis
    networks:
      - backend

networks:
  backend:
    driver: bridge
