# Generated by Django 5.1.5 on 2025-01-24 09:48

import django.db.models.deletion
import groups.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('post', models.TextField()),
                ('author_name', models.CharField(default='Anonymous', max_length=100)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_edit', models.BooleanField(default=False)),
                ('picture1', models.ImageField(blank=True, null=True, upload_to=groups.utils.generate_image_name)),
                ('picture2', models.ImageField(blank=True, null=True, upload_to=groups.utils.generate_image_name)),
                ('picture3', models.ImageField(blank=True, null=True, upload_to=groups.utils.generate_image_name)),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('public_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupSubscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('subscription_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupPostsEdits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('edit_author_name', models.CharField(default='Anonymous', max_length=100)),
                ('post_previous', models.TextField()),
                ('post_next', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.groupposts')),
            ],
        ),
    ]
