# Generated by Django 5.1.5 on 2025-01-24 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupposts',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.groups'),
        ),
        migrations.AddField(
            model_name='groupsubscribers',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.groups'),
        ),
        migrations.AddField(
            model_name='groupsubscribers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grouppostsedits',
            name='edit_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.groupsubscribers'),
        ),
        migrations.AddField(
            model_name='groupposts',
            name='author',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_admin': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.groupsubscribers'),
        ),
        migrations.AlterUniqueTogether(
            name='groupsubscribers',
            unique_together={('group', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='grouppostsedits',
            unique_together={('post', 'edit_date')},
        ),
    ]
