# Generated by Django 5.1.5 on 2025-01-28 10:18

import groups.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='avatar',
            field=models.ImageField(default='groups_avatars/default.png', upload_to=groups.utils.generate_avatar_name),
        ),
    ]
