# Generated by Django 5.1.5 on 2025-02-05 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_groups_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPostsComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=240)),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.groupsubscribers')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.groupposts')),
            ],
        ),
    ]
