# Generated by Django 5.1.5 on 2025-02-06 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_grouppostreaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPostsCommentsReactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('L', 'Like'), ('D', 'Dislike'), ('H', 'Heart')], max_length=1)),
                ('reaction_time', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.grouppostscomments')),
                ('react_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.groupsubscribers')),
            ],
        ),
    ]
