# Generated by Django 5.1.5 on 2025-02-06 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_grouppostscommentsreactions'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grouppostscommentsreactions',
            unique_together={('comment', 'react_user', 'status')},
        ),
    ]
