# Generated by Django 5.1.5 on 2025-01-21 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messenger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupposts',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.groups'),
        ),
        migrations.AddField(
            model_name='groupsubscribers',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.groups'),
        ),
        migrations.AddField(
            model_name='groupsubscribers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupposts',
            name='author',
            field=models.ForeignKey(limit_choices_to={'is_admin': True}, on_delete=django.db.models.deletion.CASCADE, to='messenger.groupsubscribers'),
        ),
        migrations.AlterUniqueTogether(
            name='groupsubscribers',
            unique_together={('group', 'user')},
        ),
    ]
