# Generated by Django 5.1.5 on 2025-01-21 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_alter_groupposts_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupposts',
            name='author',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_admin': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='messenger.groupsubscribers'),
        ),
    ]
