# Generated by Django 5.1.5 on 2025-02-10 10:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_alter_chats_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='last_message_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
