# Generated by Django 5.1.5 on 2025-01-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_alter_groupposts_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupposts',
            name='author_name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
