# Generated by Django 5.1.5 on 2025-01-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_alter_message_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('S', 'Sender'), ('R', 'Read')], default='S', max_length=1),
        ),
    ]
