# Generated by Django 5.1.5 on 2025-02-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_chats_last_message_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='last_message_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
