# Generated by Django 5.1.5 on 2025-01-27 17:15

import messenger.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_message_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=messenger.utils.generate_image_name),
        ),
    ]
