# Generated by Django 5.1.5 on 2025-01-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0006_groups_public_name_alter_groups_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='groups',
            name='public_name',
            field=models.CharField(max_length=100),
        ),
    ]
