# Generated by Django 5.1.5 on 2025-02-05 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0007_message_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('L', 'Like'), ('D', 'Dislike'), ('H', 'Heart')], max_length=1)),
                ('reaction_time', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.message')),
                ('react_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='react_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
