# Generated by Django 5.1.5 on 2025-01-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0007_alter_groups_name_alter_groups_public_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupposts',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='groupposts',
            name='title',
            field=models.CharField(default='title', max_length=100),
            preserve_default=False,
        ),
    ]
