# Generated by Django 5.1.5 on 2025-01-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0008_groupposts_slug_groupposts_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupposts',
            name='edit_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
