# Generated by Django 5.1.5 on 2025-02-13 13:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0009_remove_message_dislikes_remove_message_hearts_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chats',
            name='last_message_time',
        ),
        migrations.AlterUniqueTogether(
            name='messagereaction',
            unique_together={('reaction', 'message', 'author')},
        ),
    ]
