# Generated by Django 5.1.5 on 2025-01-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0009_groupposts_edit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupposts',
            name='is_edit',
            field=models.BooleanField(default=False),
        ),
    ]
