# Generated by Django 5.1.5 on 2025-01-21 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0010_groupposts_is_edit'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPostsEdits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('edit_author_name', models.CharField(default='Anonymous', max_length=100)),
                ('post_previous', models.TextField()),
                ('post_next', models.TextField()),
                ('edit_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.groupsubscribers')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.groupposts')),
            ],
            options={
                'unique_together': {('post', 'edit_date')},
            },
        ),
    ]
