# Generated by Django 5.1.5 on 2025-02-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0010_remove_chats_last_message_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='last_messaging_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
