# Generated by Django 5.1.5 on 2025-02-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0011_message_last_messaging_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='last_messaging_time',
        ),
        migrations.AddField(
            model_name='chats',
            name='last_messaging_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
