# Generated by Django 5.1.5 on 2025-01-23 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0011_grouppostsedits'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPostPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture1', models.ImageField(unique=True, upload_to='pictures/')),
                ('picture2', models.ImageField(upload_to='pictures/')),
                ('picture3', models.ImageField(upload_to='pictures/')),
                ('picture4', models.ImageField(upload_to='pictures/')),
                ('picture5', models.ImageField(upload_to='pictures/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_pictures', to='messenger.groupposts')),
            ],
        ),
        migrations.AddField(
            model_name='groupposts',
            name='pictures',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pictures', to='messenger.grouppostpictures'),
        ),
        migrations.AddField(
            model_name='groupposts',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thumbnail', to='messenger.grouppostpictures', to_field='picture1'),
        ),
    ]
