# Generated by Django 5.1.5 on 2025-02-18 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0012_remove_message_last_messaging_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chats',
            options={'verbose_name': 'Чат', 'verbose_name_plural': 'Чаты'},
        ),
    ]
