# Generated by Django 5.1.5 on 2025-01-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0012_grouppostpictures_groupposts_pictures_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppostpictures',
            name='picture1',
            field=models.ImageField(upload_to='pictures/'),
        ),
        migrations.AlterField(
            model_name='groupposts',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
    ]
