# Generated by Django 5.1.5 on 2025-01-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0014_remove_groupposts_pictures_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupposts',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
    ]
