# Generated by Django 5.1.5 on 2025-01-23 15:30

import messenger.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0015_alter_groupposts_picture1'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='groupposts',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to=messenger.models.generate_image_name),
        ),
    ]
