# Generated by Django 5.1.5 on 2025-02-19 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0015_alter_message_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chats',
            name='last_messaging_time',
        ),
    ]
