# Generated by Django 5.1.5 on 2025-02-20 09:28

import messenger.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0016_remove_chats_last_messaging_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='avatar',
            field=models.ImageField(blank=True, default='chats_avatars/default.png', null=True, upload_to=messenger.utils.generate_avatar_name),
        ),
    ]
