# Generated by Django 5.1.5 on 2025-02-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0018_alter_message_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagereaction',
            old_name='reaction_time',
            new_name='time',
        ),
        migrations.AlterField(
            model_name='messagereaction',
            name='reaction',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
